const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium}=require('/Users/noahsutter/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const root=path.resolve(__dirname,'../../..'),out=__dirname;
function fp(file){const bytes=fs.readFileSync(file);return{path:path.relative(root,file),bytes:bytes.length,sha256:crypto.createHash('sha256').update(bytes).digest('hex')}}
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const receipt={time:new Date().toISOString(),artifact:fp(path.join(root,'kirocrew-ec2-slide.html')),browser:browser.version(),interactions:[],exports:[],errors:[],status:'running'};try{
const page=await browser.newPage({viewport:{width:2048,height:1320},colorScheme:'light'});page.on('pageerror',e=>receipt.errors.push(String(e)));await page.goto('file://'+path.join(root,'kirocrew-ec2-slide.html'));await page.locator('.diagram-container > svg').waitFor();
if(await page.locator('html').getAttribute('data-theme')!=='light')await page.locator('#btn-theme').click();
await page.locator('#btn-node-finder').click();await page.locator('#node-finder-input').fill('Gateway');const finder=await page.locator('#node-finder').innerText();if(!finder.includes('Gateway'))throw Error('Gateway search missing');await page.keyboard.press('Enter');await page.keyboard.press('Escape');await page.locator('#node-slide-runtime').click();await page.screenshot({path:path.join(out,'runtime-focused.png')});await page.keyboard.press('Escape');receipt.interactions.push('Gateway search, result selection, runtime focus, Escape dismissal');
await page.locator('#btn-present').click();if(await page.locator('html').getAttribute('data-present')!=='true')throw Error('Presentation mode failed');await page.keyboard.press('Escape');if(await page.locator('html').getAttribute('data-present')==='true')throw Error('Presentation mode did not close');receipt.interactions.push('Presentation mode opened and Escape restored reader');
for(const format of ['svg','png']){await page.locator('#btn-export').click();const pending=page.waitForEvent('download');await page.locator('[data-format="'+format+'"]').click();const download=await pending;const file=path.join(out,'kirocrew-ec2-slide.'+format);await download.saveAs(file);if(fs.statSync(file).size<1000)throw Error('Empty export');if(format==='svg'){const s=fs.readFileSync(file,'utf8');if(!s.includes('<svg')||s.includes('<button'))throw Error('Malformed SVG export')}receipt.exports.push(fp(file));}
if(receipt.errors.length)throw Error(receipt.errors.join('\n'));receipt.status='pass';
}catch(e){receipt.status='fail';receipt.failure=String(e);process.exitCode=1}finally{fs.writeFileSync(path.join(out,'interaction-export.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));await browser.close()}})();
