const fs=require('node:fs');const path=require('node:path');const crypto=require('node:crypto');const assert=require('node:assert/strict');
const {loadPlaywright, browserOptions} = require('./browser-runtime.cjs');
const {chromium} = loadPlaywright();
const root=path.resolve(__dirname,'..'),out=path.join(root,'evidence/browser');
fs.mkdirSync(out, {recursive: true});
const fp=n=>{const b=fs.readFileSync(path.join(root,n));return {path:n,sha256:crypto.createHash('sha256').update(b).digest('hex'),bytes:b.length}};
(async()=>{const b=await chromium.launch(browserOptions());const receipt={timestamp:new Date().toISOString(),browser:b.version(),artifact:fp('kirocrew-aws-remote.html'),diagrams:['kirocrew-security-layers-browser.html','kirocrew-aws-deployment-browser.html'].map(fp),viewports:[],interactions:[],errors:[],status:'running'};try{
 const p=await b.newPage({viewport:{width:1440,height:900},colorScheme:'light'});p.on('pageerror',e=>receipt.errors.push(String(e)));await p.goto('file://'+path.join(root,'kirocrew-aws-remote.html'));
 const metrics=()=>({width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight});
 for(const [w,h] of [[1440,900],[1600,1000],[1920,1080],[2048,1320]]){await p.setViewportSize({width:w,height:h});
 for(const view of ['security','aws','reference']){await p.locator('#tab-'+view).click();assert.equal(await p.locator('#tab-'+view).getAttribute('aria-selected'),'true');
 const outer=await p.evaluate(metrics);assert(outer.scrollWidth<=w);if(view!=='reference')assert(outer.scrollHeight<=h);
 if(view==='reference'){assert.equal(await p.locator('.control').count(),15);receipt.viewports.push({w,h,view,outer,verticalScroll:'intentional reference document'});continue;}
 const f=await p.locator('#'+view+'-frame').contentFrame();await f.locator('.diagram-container > svg').waitFor();
 for(const theme of ['light','dark']){if(await f.locator('html').getAttribute('data-theme')!==theme)await f.locator('#btn-theme').click();await f.locator('body').evaluate(async()=>{await Archify.viewerChromeLayout.whenStable();await Archify.readerLayout.whenStable();await Archify.viewerChromeLayout.whenStable()});
 const inner=await f.locator('body').evaluate(metrics);assert(inner.scrollWidth<=inner.width,JSON.stringify({view,w,h,inner}));assert(inner.scrollHeight<=inner.height,JSON.stringify({view,w,h,inner}));const caveat=await f.locator(".browser-caveat").evaluate(e=>({top:e.getBoundingClientRect().top,bottom:e.getBoundingClientRect().bottom}));assert(caveat.bottom<=inner.height,JSON.stringify({view,theme,w,h,caveat,inner}));receipt.viewports.push({w,h,view,theme,outer,inner,caveat});
 if(w===1440||w===2048)await p.screenshot({path:path.join(out,`viewer-${view}-${w}-${theme}.png`)});
 }} }
 await p.setViewportSize({width:1440,height:900});await p.locator('#tab-security').focus();await p.keyboard.press('ArrowRight');assert.equal(await p.locator('#tab-aws').getAttribute('aria-selected'),'true');await p.keyboard.press('Home');assert.equal(await p.locator('#tab-security').getAttribute('aria-selected'),'true');await p.keyboard.press('ArrowLeft');assert.equal(await p.locator('#tab-reference').getAttribute('aria-selected'),'true');await p.keyboard.press('End');assert.equal(await p.locator('#tab-reference').getAttribute('aria-selected'),'true');await p.locator('#expand-controls').click();assert.equal(await p.locator('.control details[open]').count(),15);await p.locator('#collapse-controls').click();assert.equal(await p.locator('.control details[open]').count(),0);receipt.interactions.push('Roving keyboard tabs, Home/End/arrow activation, 15 reference details expand and collapse');await p.screenshot({path:path.join(out,'viewer-reference.png')});
 await p.locator('#tab-security').click();const f=await p.locator('#security-frame').contentFrame();await f.locator('#btn-theme').click();await f.locator('#btn-node-finder').click();await f.locator('#node-finder-input').fill('Endpoint');const results=await f.locator('#node-finder').innerText();assert(results.includes('Endpoint'));await p.keyboard.press('Enter');await p.keyboard.press('Escape');await f.locator('#node-endpoint-control').click();await p.screenshot({path:path.join(out,'endpoint-focused.png')});await p.keyboard.press('Escape');receipt.interactions.push('Find Endpoint, select result, focus endpoint and dismiss with Escape');
 await f.locator('[data-view="in"]').click();assert(Number(await f.locator('.diagram-container > svg').getAttribute('data-view-scale'))>1);await p.screenshot({path:path.join(out,'endpoint-zoom.png')});await f.locator('[data-view="out"]').click();await f.locator('[data-view="reset"]').click();assert.equal(Number(await f.locator('.diagram-container > svg').getAttribute('data-view-scale')),1);receipt.interactions.push('Zoom in/out and reset camera');
 await f.locator('#btn-present').click();assert.equal(await f.locator('html').getAttribute('data-present'),'true');await p.keyboard.press('Escape');assert.notEqual(await f.locator('html').getAttribute('data-present'),'true');receipt.interactions.push('Presentation stage opens and Escape restores reader');
 for(const view of ['security','aws']){await p.locator('#tab-'+view).click();const frame=await p.locator('#'+view+'-frame').contentFrame();for(const format of ['svg','png']){await frame.locator('#btn-export').click();const pending=p.waitForEvent('download');await frame.locator('[data-format="'+format+'"]').click();const d=await pending;const file=path.join(out,`${view}-browser-export.${format}`);await d.saveAs(file);assert(fs.statSync(file).size>1000);if(format==='svg'){const s=fs.readFileSync(file,'utf8');assert(s.includes('<svg'));assert(!s.includes('<button'));if(view==='security'){assert(s.includes('.ep-shell {'));assert(s.includes('.ep-icon {'));}}receipt.interactions.push(view+' '+format+' export downloaded');}}
 await p.goto('file://'+path.join(root,'kirocrew-aws-remote.html')+'#reference');assert.equal(await p.locator('#tab-reference').getAttribute('aria-selected'),'true');receipt.interactions.push('Direct reference fragment loads correct view');assert.deepEqual(receipt.errors,[]);receipt.status='pass';
 }catch(e){receipt.status='fail';receipt.failure=String(e);process.exitCode=1;}finally{fs.writeFileSync(path.join(out,'integrated-browser-receipt.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify({status:receipt.status,failure:receipt.failure,measurements:receipt.viewports.length,interactions:receipt.interactions}));await b.close()}})();
